---
title: "Phyloseq"
author: "Briteal"
date: "2024-04-18"
output: html_document
---

# load required packages
```{r}
library(phyloseq)
library(dplyr)
library(BiMiCo)
```

# load taxa and seqtab.nochim
```{r}
load("RData/taxa.RData")
load("RData/seqtab.nochim.RData")
```

#import metadata 
```{r}
metadata<-read.csv("metadata.csv", header=TRUE, row.names = 1)
```

#create phyloseq object
```{r}
#make sure the seqtab.nochim and taxa objects are loaded
physeq <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows = FALSE), sample_data(metadata), tax_table(taxa))
physeq
```

# transform sample counts
```{r}
# convert from raw to abundance (a percentage)
physeq <- transform_sample_counts(physeq, function(abund) 1*(abund>0))
physeq
```

# remove the sequence itself and repalce with ASV
```{r}
dna <- Biostrings::DNAStringSet(taxa_names(physeq))
names(dna) <- taxa_names(physeq)
physeq <- merge_phyloseq(physeq, dna)
taxa_names(physeq) <- paste0("ASV", seq(ntaxa(physeq)))
physeq # to see which reads account for it, so ASV is where we look for seqs
```

# remove mt and chlorplast matches. remove all non bacti seqs (needs dplyr package to run)
```{r}
physeq <- physeq %>% subset_taxa( Family!= "Mitochondria" | is.na(Family) & Order!="Chloroplast" | is.na(Order) )
#subset is gonna take everything that is mt out
physeq
```

#remove all non bacti seqs
```{r}
physeq<-rm_nonbac(physeq)
physeq
```

#save physeq objects to load later
```{r}
save(physeq, file="RData/physeq.RData")
```